import json

def create_notebook(filename, cells):
    notebook = {
        "cells": cells,
        "metadata": {
            "kernelspec": {
                "display_name": "Python 3",
                "language": "python",
                "name": "python3"
            }
        },
        "nbformat": 4,
        "nbformat_minor": 4
    }
    with open(filename, 'w', encoding='utf-8') as f:
        json.dump(notebook, f, indent=2)

def md_cell(text):
    return {"cell_type": "markdown", "metadata": {}, "source": [text]}

def code_cell(code):
    return {"cell_type": "code", "execution_count": None, "metadata": {}, "outputs": [], "source": [code]}

nb4_cells = [
    md_cell("# Modelado Predictivo de Riesgo de Puntos Críticos\nEn este notebook entrenaremos y compararemos Regresión Logística, Random Forest y Gradient Boosting. También usaremos SHAP para interpretabilidad y K-Means para descubrir zonas territoriales."),
    code_cell("import geopandas as gpd\nimport pandas as pd\nimport numpy as np\nimport joblib\nimport matplotlib.pyplot as plt\nimport seaborn as sns\nimport shap\nimport os\n\nfrom sklearn.model_selection import train_test_split\nfrom sklearn.linear_model import LogisticRegression\nfrom sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier\nfrom sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix, roc_auc_score\nfrom sklearn.cluster import KMeans\n\n# Definir directorios\nMODEL_BASE = '../03_MODELO'\nDATASET_DIR = f'{MODEL_BASE}/01_dataset_modelo'\nTRAINED_DIR = f'{MODEL_BASE}/04_modelos_guardados'\nPRED_DIR = f'{MODEL_BASE}/05_predicciones'\nRESULTS_DIR = f'{MODEL_BASE}/07_resultados'\nEXPLAIN_DIR = f'{MODEL_BASE}/06_explicabilidad'\n\n# Cargar dataset\ndf_geo = gpd.read_file(f'{DATASET_DIR}/dataset_modelo.gpkg')\ndf = df_geo.drop(columns='geometry').copy()\nprint(\"Dataset cargado:\", df.shape)"),
    code_cell("# 1. Definir Features y Target\n# Features: descartamos el id_celda, y el target. También descartamos la cantidad de puntos críticos ya que el target está basado en él (para evitar Leakage directo si queremos predecir nuevas zonas)\n\n# RECALCULAR TARGET CORRECTAMENTE (El target previo era 1 para todo debido a cuantiles 0)\numbral_reportes = df[df['num_reportes'] > 0]['num_reportes'].quantile(0.75) if df['num_reportes'].max() > 0 else 1\ndf['target_riesgo'] = np.where((df['num_puntos_criticos'] > 0) | (df['num_reportes'] >= umbral_reportes), 1, 0)\nprint(\"Distribución corregida del target:\", df['target_riesgo'].value_counts().to_dict())\n\nfeatures = ['num_reportes', 'num_cestas', 'tiene_macroruta', 'dist_cesta_mas_cercana', 'dist_punto_critico']\ntarget = 'target_riesgo'\n\nX = df[features]\ny = df[target]\n\n# Split de los datos\n# Idealmente Spatial CV, usaremos train_test_split con stratify para mantener la proporción de riesgo\nX_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=42, stratify=y)\nprint(\"Train size:\", X_train.shape, \"Test size:\", X_test.shape)"),
    code_cell("# 2. Entrenamiento y Evaluación de Modelos\n\nmodelos = {\n    'Logística': LogisticRegression(random_state=42, max_iter=1000),\n    'Random Forest': RandomForestClassifier(random_state=42, n_estimators=100, class_weight='balanced'),\n    'Gradient Boosting': GradientBoostingClassifier(random_state=42, n_estimators=100)\n}\n\nresultados = []\n\nfor nombre, modelo in modelos.items():\n    # Entrenar\n    modelo.fit(X_train, y_train)\n    \n    # Guardar modelo\n    joblib.dump(modelo, f\"{TRAINED_DIR}/modelo_{nombre.replace(' ', '_').lower()}.pkl\")\n    \n    # Predecir\n    y_pred = modelo.predict(X_test)\n    y_proba = modelo.predict_proba(X_test)[:, 1] if hasattr(modelo, 'predict_proba') else [0]*len(y_test)\n    \n    # Métricas\n    acc = accuracy_score(y_test, y_pred)\n    prec = precision_score(y_test, y_pred, zero_division=0)\n    rec = recall_score(y_test, y_pred, zero_division=0)\n    f1 = f1_score(y_test, y_pred, zero_division=0)\n    roc = roc_auc_score(y_test, y_proba) if len(np.unique(y_test))>1 else 0\n    \n    resultados.append({\n        'Modelo': nombre,\n        'Accuracy': acc,\n        'Precision': prec,\n        'Recall': rec,  # Fundamental no dejar falsos negativos\n        'F1': f1,\n        'ROC-AUC': roc\n    })\n\ndf_resultados = pd.DataFrame(resultados)\nprint(\"\\n--- RESULTADOS DE LOS MODELOS ---\")\nprint(df_resultados)\ndf_resultados.to_csv(f\"{RESULTS_DIR}/matriz_modelos.csv\", index=False)"),
    code_cell("# 3. Matriz de Confusión del Mejor Modelo (asumamos Random Forest como principal)\nbest_model = modelos['Random Forest']\ny_pred_best = best_model.predict(X_test)\ncm = confusion_matrix(y_test, y_pred_best)\n\nplt.figure(figsize=(6, 4))\nsns.heatmap(cm, annot=True, fmt='d', cmap='Blues')\nplt.title('Matriz de Confusión - Random Forest')\nplt.ylabel('Real')\nplt.xlabel('Predicción')\nplt.savefig(f\"{RESULTS_DIR}/matriz_confusion.png\")\nplt.show()"),
    code_cell("# 4. Interpretabilidad: Feature Importance y SHAP\n# Feature Importance de Random Forest\nimportances = best_model.feature_importances_\nfi_df = pd.DataFrame({'Feature': features, 'Importancia': importances}).sort_values(by='Importancia', ascending=False)\nprint(\"\\nFeature Importance:\\n\", fi_df)\nfi_df.to_csv(f\"{EXPLAIN_DIR}/feature_importance.csv\", index=False)\n\n# SHAP\n# Usamos TreeExplainer para Random Forest\nexplainer = shap.TreeExplainer(best_model)\nshap_obj = explainer(X_test)\n\n# Manejar diferentes formatos devueltos por versiones de SHAP\nif hasattr(shap_obj, 'values') and len(shap_obj.values.shape) == 3:\n    shap_vals_plot = shap_obj[:, :, 1]\nelif isinstance(shap_obj, list):\n    shap_vals_plot = shap_obj[1]\nelse:\n    shap_vals_plot = shap_obj\n\n# Graficar SHAP summary plot\nplt.figure()\nshap.summary_plot(shap_vals_plot, X_test, show=False)\nplt.savefig(f\"{EXPLAIN_DIR}/shap_summary.png\", bbox_inches='tight')\nplt.show()"),
    code_cell("# 5. Clustering con K-Means\n# Normalizamos las features numéricas para clustering\nfrom sklearn.preprocessing import StandardScaler\nscaler = StandardScaler()\nX_scaled = scaler.fit_transform(X)\n\nkmeans = KMeans(n_clusters=3, random_state=42, n_init=10)\nclusters = kmeans.fit_predict(X_scaled)\ndf_geo['cluster'] = clusters\nprint(\"\\nDistribución de clusters:\\n\", df_geo['cluster'].value_counts())"),
    code_cell("# 6. Predicción Final sobre toda Bogotá y guardado\n# Calculamos la probabilidad de riesgo para TODA la grilla\nprobabilidades = best_model.predict_proba(X)[:, 1]\ndf_geo['probabilidad_riesgo'] = probabilidades\n\n# Clasificación (Alto, Medio, Bajo)\ndf_geo['nivel_riesgo'] = np.where(probabilidades >= 0.67, '🔴 Alto',\n                                  np.where(probabilidades >= 0.34, '🟡 Medio', '🟢 Bajo'))\n\n# Asignar prioridad de intervención básica\n# Prioridad = Probabilidad * num_reportes (como variable de persistencia)\ndf_geo['indice_prioridad'] = df_geo['probabilidad_riesgo'] * (df_geo['num_reportes'] + 1)\ndf_geo = df_geo.sort_values(by='indice_prioridad', ascending=False)\n\n# Definir Acción Recomendada basada en reglas y riesgo\ndef recomendar_accion(row):\n    if row['nivel_riesgo'] == '🔴 Alto':\n        if row['tiene_macroruta'] == 0:\n            return 'Priorizar revisión de cobertura de barrido'\n        elif row['num_cestas'] == 0:\n            return 'Evaluar instalación de infraestructura de cestas'\n        else:\n            return 'Inspección prioritaria por alta concentración'\n    elif row['nivel_riesgo'] == '🟡 Medio':\n        return 'Monitoreo preventivo'\n    else:\n        return 'Seguimiento normal'\n\ndf_geo['accion_recomendada'] = df_geo.apply(recomendar_accion, axis=1)\n\n# Guardar la capa de salida predictiva\ndf_geo.to_file(f\"{PRED_DIR}/riesgo_predicho.gpkg\", driver='GPKG')\n\n# Guardar top de zonas prioritarias\ntop_zonas = df_geo[['id_celda', 'nivel_riesgo', 'probabilidad_riesgo', 'indice_prioridad', 'accion_recomendada']].head(20)\ntop_zonas.to_csv(f\"{RESULTS_DIR}/ranking_zonas.csv\", index=False)\nprint(\"\\nPredicciones guardadas exitosamente.\")")
]

create_notebook('05_modelos.ipynb', nb4_cells)
print("Notebook 05_modelos.ipynb creado.")
